---
driver:
    name: docker
    test_base_path: test
    use_sudo: false # because of https://github.com/test-kitchen/kitchen-docker/issues/207

provisioner:
    name: puppet_apply
    manifest: site.pp
    puppet_debug: true
    ignored_paths_from_root:
        - "spec"
        - "vendor"

platforms:
    -   name: ubuntu-22.04
        provisioner:
            name: puppet_apply
            puppet_apt_collections_repo: "https://apt.puppetlabs.com/puppet-release-jammy.deb"
            custom_facts:
                GITHUB_USE_OAUTH: <%= ENV['GITHUB_USE_OAUTH'] || false %>
                GITHUB_USE_AUTH: <%= ENV['GITHUB_USE_AUTH'] || false %>
                GITHUB_USERNAME: <%= ENV['GITHUB_USERNAME'] %>
                GITHUB_PASSWORD: <%= ENV['GITHUB_PASSWORD'] %>

verifier:
    name: serverspec

suites:
    -   name: default
        verifier:
            custom_install_command: sudo ln -s /usr/bin/bundle3.0 /usr/local/bin/bundle
            bundler_path: '/usr/local/bin'
            rspec_path: '/usr/local/bin'
