---
driver:
  name: docker
  test_base_path: test
  use_sudo: false # because of https://github.com/test-kitchen/kitchen-docker/issues/207

provisioner:
  name: puppet_apply
  manifest: site.pp
  puppet_debug: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    provisioner:
      name: puppet_apply
      puppet_apt_repo: "http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb"
  - name: ubuntu-16.04-puppet4
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu
    provisioner:
      name: puppet_apply
      require_puppet_collections: true
      puppet_apt_collections_repo: "http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb"


suites:
  - name: default
    run_list:
