Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Max: 50

Metrics/ParameterLists:
    Max: 10

Metrics/MethodLength:
    Max: 35

Metrics/CyclomaticComplexity:
    Max: 7

Metrics/AbcSize:
    Max: 16
